name: "【Docker】Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-htmlbeautifier:
    name: Run htmlbeautifier
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      SMTP_ADDRESS: 'smtp.gmail.com'
      SMTP_PORT: '587'
      SMTP_DOMAIN: 'gmail.com'
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_AUTHENTICATION: 'plain'
      SMTP_ENABLE_STARTTLS_AUTO: 'true'

    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: run htmlbeautifier on docker-compose
      run: |
        docker compose build
        docker compose run --rm web bin/setup
        docker compose run --rm web bin/htmlbeautifier
        git diff --exit-code
